version: '3'
services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - http_proxy=
      - https_proxy=
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - TOGGL_API=${TOGGL_API}
      - TODOIST_API=${TODOIST_API}
    network_mode: bridge
    volumes:
      - ./config:/app/config # to mount json and yaml file
